{% set version = "1.0" %}

package:
  name: gridutils
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/sakov/gridutils-c/archive/v{{ version }}.tar.gz
  sha256: 358e93d2e3431d9e2d4c0574d25d97dd26585204e1e8407e817429f40ebf406e

build:
  number: 2

requirements:
  build:
    - toolchain
    - posix  # [win]
    - m2w64-toolchain  # [win]
    - nn
    - csa
  run:
    - nn
    - csa

test:
  commands:
    # *nix
    - getbounds -h  # [not win]
    - getnodes -h  # [not win]
    - gridbathy -h  # [not win]
    - insertgrid -h  # [not win]
    - setbathy -h  # [not win]
    - subgrid -h  # [not win]
    - xyij -h  # [not win]
    # win
    - getbound.exe -h  # [win]
    - getnodes.exe -h  # [win]
    - gridbathy.exe -h  # [win]
    - insertgrid.exe -h  # [win]
    - setbathy.exe -h  # [win]
    - subgrid.exe -h  # [win]
    - xyij.exe -h  # [win]
    - conda inspect linkages -p $PREFIX gridutils  # [not win]
    - conda inspect objects -p $PREFIX gridutils  # [osx]

about:
  home: https://github.com/sakov/gridutils-c
  license: BSD 2-Clause
  # license_file: LICENSE
  summary: 'C library functions and command line utilities for working with curvilinear grids.'

extra:
  recipe-maintainers:
    - ocefpaf
